import { PROVIDERS, tokenSeries, timeTotals, dayUTC, copilotAllowance, copilotBalance, activitySeries, liveSegments, estimatedTime } from '../core/model.js';
const $ = selector => document.querySelector(selector);
const api = window.tracker;
let dialogSequence = 0;
let state, provider = 'all', subscription = 'all', activityMetric = 'auto', toastTimer, loadSequence = 0;
const dialog = $('#dialog');
const esc = value => String(value ?? '').replace(/[&<>"']/g, c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const number = n => n == null ? '—' : new Intl.NumberFormat().format(n);
const compact = n => n == null ? '—' : new Intl.NumberFormat(undefined,{notation:'compact',maximumFractionDigits:1}).format(n);
const icon = name => `<span class="icon" aria-hidden="true"><svg viewBox="0 0 24 24">${({grid:'<rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/>',plus:'<path d="M12 5v14M5 12h14"/>',refresh:'<path d="M20 7v5h-5M4 17v-5h5"/><path d="M6 7a7 7 0 0 1 12-2l2 3M4 16l2 3a7 7 0 0 0 12-2"/>',settings:'<path d="M4 7h16M4 17h16"/><circle cx="9" cy="7" r="3" fill="currentColor"/><circle cx="16" cy="17" r="3" fill="currentColor"/>',shield:'<path d="M12 3l8 3v5c0 5-4 8-8 10-4-2-8-5-8-10V6zM8 12l3 3 5-6"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',arrow:'<path d="M5 12h14M13 6l6 6-6 6"/>'})[name] || ''}</svg></span>`;
const time = ms => { if(ms>0&&ms<60000)return `${Math.floor(ms/1000)}s`; const minutes = Math.floor(ms/60000); return `${Math.floor(minutes/60)}h ${String(minutes%60).padStart(2,'0')}m`; };
function age(value) { if (!value) return 'Not refreshed yet'; const secs = Math.max(0,Math.floor((Date.now()-value)/1000)); return secs < 60 ? 'Updated just now' : secs < 3600 ? `Updated ${Math.floor(secs/60)}m ago` : `Updated ${Math.floor(secs/3600)}h ago`; }
function reset(value) { if (!value) return 'Reset time unavailable'; const mins = Math.ceil((value-Date.now())/60000); const date = new Date(value).toLocaleString(undefined,{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}); return mins <= 0 ? `Reset time passed · awaiting provider update (${date})` : `Resets in ${mins >= 60 ? `${Math.floor(mins/60)}h ${mins%60}m` : `${mins}m`} · ${date}`; }
function toast(text) { $('#toast').textContent = text; $('#toast').classList.add('show'); clearTimeout(toastTimer); toastTimer = setTimeout(()=>$('#toast').classList.remove('show'),6000); }
async function call(method,...args) { const result = await api[method](...args); if (!result.ok) throw new Error(result.error); return result.value; }
async function load() { const sequence = ++loadSequence; const value = await call('state'); if (sequence !== loadSequence) return; state = value; render(); updateConnectionDialog(); }
const connectionStatus = a => a.provider === 'claude' ? (a.claudeWeb?(a.claudeWeb.lastReceived?'Claude website linked':'Waiting for browser reading'):a.loginPending?'Complete sign-in in your browser':a.connected?'Signed in with Claude':a.logPath?'Local history linked':'Not signed in') : a.loginPending ? 'Complete sign-in in your browser' : a.connected ? 'Connected' : a.provider === 'other' ? 'Focus timer only' : 'Not connected';
function updateConnectionDialog() {
  if (!dialog.open || !dialog.dataset.account) return;
  const a = state.accounts.find(a=>a.id===dialog.dataset.account); if (!a) return;
  const status = $('#connection-status');
  if (status) status.textContent = connectionStatus(a);
  const loginButton = dialog.querySelector('[data-action="login"]');
  if (loginButton) { loginButton.textContent = a.loginPending ? 'Sign-in in progress…' : a.connected ? 'Sign in again' : 'Sign in with ChatGPT'; loginButton.disabled = !!a.loginPending; }
  if (!a.loginPending) dialog.querySelector('[data-action="cancel-login"]')?.remove();
  if (a.error) $('#dialog-error').innerHTML = `<div class="error">${esc(a.error)}</div>`;
}
function selectedAccounts() { return state.accounts.filter(a=>(provider === 'all' || a.provider === provider) && (subscription === 'all' || a.subscription === subscription)); }
const METRICS = { tokens:{label:'Tokens',unit:'tokens',color:'#a8c8ff'}, credits:{label:'AI credits',unit:'AI credits',color:'#eac977'}, requests:{label:'Requests',unit:'requests',color:'#d7b0ef'}, active:{label:'Active time',unit:'minutes',color:'#caf586'}, focus:{label:'Focus',unit:'minutes',color:'#9aaea3'} };
function activity() {
  const accounts=selectedAccounts();
  const metric=activityMetric==='auto' ? accounts.some(a=>a.tokens) ? 'tokens' : accounts.some(a=>a.provider==='copilot' && a.billingMode!=='premium_request') ? 'credits' : accounts.some(a=>a.provider==='copilot') ? 'requests' : 'tokens' : activityMetric;
  const series=activitySeries(accounts,metric,liveSegments(state.segments,state.active)), known=series.filter(d=>d.total!==null);
  return {metric,series,known,total:known.reduce((n,d)=>n+d.total,0),...METRICS[metric]};
}
function render() {
  const accounts=selectedAccounts(), ids=accounts.map(a=>a.id), totals=timeTotals(liveSegments(state.segments,state.active),ids), data=activity(), today=data.series.at(-1);
  const automatic=estimatedTime(accounts);
  const activeId=document.activeElement?.id;
  const providerRows=Object.entries(PROVIDERS).filter(([key])=>state.accounts.some(a=>a.provider===key));
  $('#sidebar').innerHTML=`<div class="brand"><div class="brand-mark">↗</div><div>AI Usage<span class="brand-sub">YOUR DAILY CHECK-IN</span></div><span class="status-live"><span class="dot"></span>${state.accounts.some(a=>a.refreshing)?'Syncing…':'Local & private'}</span></div><nav aria-label="Providers"><button class="nav-item ${provider==='all'?'selected':''}" data-action="filter" data-id="all">Overview <span class="nav-count">${state.accounts.length}</span></button>${providerRows.map(([key,p])=>`<button class="nav-item ${provider===key?'selected':''}" data-action="filter" data-id="${key}"><span class="dot" style="background:${p.color}"></span>${p.name}<span class="nav-count">${state.accounts.filter(a=>a.provider===key).length}</span></button>`).join('')}</nav>`;
  const subs=[...new Set(state.accounts.map(a=>a.subscription).filter(Boolean))];
  const current=state.active && state.accounts.find(a=>a.id===state.active.accountId);
  $('#main').innerHTML=`<section class="intro"><div><h1>Your AI, in view.</h1><p>${new Date().toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric'})} · Refresh every ${state.settings.pollSeconds/60} min</p></div><div class="actions"><button class="small quiet" data-action="refresh" aria-label="Refresh" title="Refresh" ${state.accounts.some(a=>a.refreshing)?'disabled':''}>${icon('refresh')}</button><button class="small" data-action="add" aria-label="Add account" title="Add account">${icon('plus')}</button></div></section>
  ${current?`<div class="focus-banner"><span>Focusing · <b>${esc(current.label)}</b> <strong id="focus-clock"></strong></span><button class="small quiet" data-action="stop">Stop timer</button></div>`:state.lastPause&&state.lastPause!=='App closed'?`<div class="pause-note">${esc(state.lastPause)}</div>`:''}
  <section class="summary" aria-label="Usage summary"><div class="stat"><div class="eyebrow">${esc(data.label)} today</div><div class="stat-value" title="${number(today.total)}">${compact(today.total)}</div><div class="stat-note">${today.total===null?'Source not linked yet':data.metric==='focus'?'Recorded focus minutes':`${today.reporting} source${today.reporting===1?'':'s'} · UTC`}</div></div><div class="stat"><div class="eyebrow">Working today · est.</div><div class="stat-value" id="active-today">${automatic.reporting?time(automatic.todayMs):'—'}</div><div class="stat-note">${automatic.reporting?`${time(automatic.monthMs)} this month · local activity`:'Needs local session history'}</div></div></section>
  <section aria-labelledby="accounts-title"><div class="section-head"><h2 id="accounts-title">Your subscriptions <span class="muted">(${accounts.length})</span></h2><label class="filter" for="subscription-filter"><span class="sr-only">Plan</span><select id="subscription-filter" aria-label="Plan"><option value="all">All subscriptions</option>${subs.map(s=>`<option value="${esc(s)}" ${subscription===s?'selected':''}>${esc(s)}</option>`).join('')}</select></label></div><div class="cards">${accounts.length?accounts.map(a=>accountCard(a,totals.byAccount[a.id])).join(''):`<div class="empty"><h2>${state.accounts.length?'No matching accounts':'One place for all your AI.'}</h2><p>${state.accounts.length?'Choose another provider or plan.':'Connect an account to see its usage and reset times.'}</p><button class="primary" data-action="${state.accounts.length?'reset-filters':'add'}">${state.accounts.length?'Clear filters':'Connect an account'}</button></div>`}</div></section>
  <section class="chart-panel" aria-labelledby="chart-title" style="--chart-color:${data.color}"><div class="chart-header"><div><h2 id="chart-title">Daily usage</h2><p>Last 30 days · ${['focus','active'].includes(data.metric)?'local dates':'UTC dates'}</p></div><div class="chart-total">${data.known.length?compact(data.total):'—'}<small>${data.unit} · ${data.known.length}/30 days</small></div></div><div class="metric-tabs" role="tablist" aria-label="Usage metric">${Object.entries(METRICS).filter(([key])=>(key!=='requests'||accounts.some(a=>a.billingMode==='premium_request'))).map(([key,m])=>`<button id="metric-${key}" role="tab" aria-selected="${data.metric===key}" data-action="metric" data-id="${key}">${m.label}</button>`).join('')}</div>${chart(data)}${activityHelp(accounts,data)}<div class="chart-footer"><span>Hover, tap, or use arrow keys for daily totals.</span><button class="link" data-action="daily">Daily values</button></div></section>
  <footer class="panel-tools"><button class="small quiet" data-action="window-toggle" title="Switch between side panel and expanded view">${icon('grid')} <span>Resize view</span></button><button class="small quiet" data-action="pin" aria-pressed="${!!state.settings.alwaysOnTop}">${state.settings.alwaysOnTop?'Unpin':'Pin on top'}</button><button class="small quiet" data-action="settings">${icon('settings')} Settings</button></footer>`;
  $('#subscription-filter').addEventListener('change',e=>{subscription=e.target.value;render();});
  for(const bar of document.querySelectorAll('.bar-hit')) {
    const show=()=>{document.querySelector('.bar-hit.active')?.classList.remove('active');bar.classList.add('active');$('#chart-tooltip').textContent=bar.getAttribute('aria-label');};
    bar.addEventListener('mouseenter',show);bar.addEventListener('focus',show);bar.addEventListener('click',show);
    bar.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();const i=Number(bar.dataset.index)+(e.key==='ArrowRight'?1:-1);document.getElementById(`day-${Math.max(0,Math.min(29,i))}`)?.focus();}});
  }
  if(activeId && !dialog.open) document.getElementById(activeId)?.focus({preventScroll:true});
  updateClock();
}
function activityHelp(accounts,data) {
  const warnings=accounts.map(a=>['tokens','active'].includes(data.metric)?a.tokens?.warning:['credits','requests'].includes(data.metric)?a.usageHistory?.warning:null).filter(Boolean);
  const links=['tokens','active'].includes(data.metric)?accounts.filter(a=>['codex','claude'].includes(a.provider)&&!a.logPath):[];
  return `<div class="activity-source">${data.metric==='tokens'?'Reported tokens only. Local history covers linked folders, not every device.':data.metric==='active'?'Estimated time between local activity events. Gaps over 5 minutes excluded; overlapping sessions counted once. This is not exact human working time.':data.metric==='focus'?'Time recorded with the focus timer on this device.':'Daily GitHub billing reports. AI credits and requests are separate from tokens.'}${data.known.length<30?' Missing days remain unavailable.':''}${accounts.some(a=>a.status==='error')?' Some sources are showing saved readings.':''}${warnings.length?`<details><summary>Partial history · view details</summary>${[...new Set(warnings)].map(esc).join('<br>')}</details>`:''}${links.map(a=>`<button class="link source-link" data-action="logs-dialog" data-id="${a.id}">Link ${esc(a.label)} token history ↗</button>`).join('')}${!data.known.length&&!links.length&&data.metric==='tokens'?'<p>These connections do not supply token history. Select AI credits for Copilot daily usage.</p>':''}</div>`;
}
function accountCard(a,t = {todayMs:0,monthMs:0}) {
  const p=PROVIDERS[a.provider],focused=state.active?.accountId===a.id,balance=copilotBalance(a);
  const quotas=balance?[{name:'Monthly AI credits · estimated',...balance}]:a.claudeWeb?(a.quotas||[]).filter(q=>q.resetsAt>Date.now()):a.quotas;
  const stale=a.status==='error'||(a.lastSuccess&&Date.now()-a.lastSuccess>state.settings.pollSeconds*2000);
  const status=a.refreshing?'Refreshing':a.loginPending?'Sign-in pending':stale?'Needs attention':a.status==='ready'?(a.provider==='claude'?(a.connected?'Signed in with Claude':'Local history linked'):'Connected'):'Setup';
  return `<article class="account compact-account ${focused?'focused':''}" style="--provider:${p.color}" data-account="${a.id}"><div class="account-head"><div class="provider-icon">${p.short}</div><div class="account-heading"><h3>${esc(a.label)} <span class="plan-label">${esc(a.subscription)}</span></h3></div><span class="connection-dot ${stale?'warning':''}" title="${status} · ${age(a.lastSuccess)}" aria-label="${status}"></span><button class="manage" data-action="manage" data-id="${a.id}" aria-label="Manage ${esc(a.label)}">⋯</button></div>
  ${quotas?.length?quotas.map(q=>`<div class="quota"><div class="quota-label"><span>${esc(q.name)}</span><strong>${Math.round(q.remainingPercent)}% left</strong></div><div class="track" role="meter" aria-label="${esc(q.name)} remaining" aria-valuenow="${q.remainingPercent}" aria-valuemin="0" aria-valuemax="100"><div class="fill" style="width:${q.remainingPercent}%"></div></div><div class="reset">${reset(q.resetsAt)}</div></div>`).join(''):`<div class="quota unavailable"><strong>Remaining usage unavailable</strong>${a.provider==='copilot'&&a.billingMode!=='premium_request'?copilotAllowance(a)?'Waiting for this month’s usage.':'Set your allowance in Details.':a.provider==='codex'&&!a.connected?'Sign in with ChatGPT in Details.':a.provider==='claude'&&a.claudeWeb?'Waiting for a current reading from Claude in your browser.':'No subscription quota from this source.'}</div>`}
  ${balance?`<div class="billing">${number(balance.remaining)} <small>AI credits remaining</small></div>${balance.overage?`<div class="source-note">${number(balance.overage)} credits beyond the included allowance</div>`:''}`:a.usage?`<div class="billing">${number(a.usage.value)} <small>${esc(a.usage.unit)} used · ${esc(a.usage.period)}</small></div>`:''}
  ${a.claudeWeb?`<div class="source-note">${a.claudeWeb.lastReceived?`Browser reading · ${esc(age(a.claudeWeb.lastReceived).replace('Updated','observed'))}`:'Connect the companion, then use Claude normally.'}</div>`:''}
  ${a.error?`<div class="error">${esc(a.error)}</div>`:''}
  <div class="account-bottom"><div class="account-activity">${a.tokens?`<span title="${esc(a.tokens.source)}${a.tokens.warning?' · partial local history':''}">${compact(a.tokens.days[dayUTC()])} tokens today${a.tokens.warning?' · partial':''}</span>`:balance?`<span>${compact(balance.used)} / ${compact(balance.allowance)} used · estimated</span>`:['codex','claude'].includes(a.provider)?`<button class="link" data-action="logs-dialog" data-id="${a.id}">Link token history</button>`:''}<span class="account-focus-total" data-focus-total="${a.id}">${t.todayMs>0?`${time(t.todayMs)} focus`:''}</span></div><button class="link card-details" data-action="manage" data-id="${a.id}">Details</button><button class="small ${focused?'primary':'quiet'}" data-action="${focused?'stop':'start'}" data-id="${a.id}" aria-label="${focused?'Stop focus':'Start focus'}">${icon('clock')} ${focused?'Stop':'Focus'}</button></div></article>`;
}
function chart(data) {
  const {series,unit,metric}=data,max=Math.max(1,...series.map(d=>d.total||0));
  return `<div class="chart-stage"><div class="chart-bars" role="group" aria-label="Daily ${unit} usage, last 30 days">${series.map((d,i)=>`<button id="day-${i}" class="bar-hit" data-index="${i}" aria-label="${d.day}: ${d.total===null?'unavailable':`${number(d.total)} ${unit}`}; ${d.reporting} of ${d.accounts} sources reporting"><span class="bar ${d.total===null?'unknown':d.total===0?'zero':''}" style="height:${d.total===null||d.total===0?0:Math.max(1,(d.total/max)*100)}%"></span></button>`).join('')}</div><div class="y-axis"><span>${compact(max)}</span><span>${compact(max/2)}</span><span>0</span></div></div><div class="chart-labels">${[0,7,14,21,29].map(i=>`<span>${new Date(series[i].day+'T12:00:00Z').toLocaleDateString(undefined,{month:'short',day:'numeric',timeZone:'UTC'})}</span>`).join('')}</div><div id="chart-tooltip" class="chart-tooltip" aria-live="polite">${data.known.length?`${number(series.at(-1).total)} ${unit} today · ${number(series.at(-2).total)} yesterday`:metric==='tokens'?'Link local history below to see reported tokens.':'Waiting for daily reports. Missing data is not zero.'}</div>`;
}
function updateClock() {
  if(!state?.active)return;
  const totals=timeTotals(liveSegments(state.segments,state.active),selectedAccounts().map(a=>a.id));
  if($('#focus-today'))$('#focus-today').textContent=time(totals.todayMs);
  if($('#focus-month'))$('#focus-month').textContent=time(totals.monthMs);
  for(const el of document.querySelectorAll('[data-focus-total]')) el.textContent=totals.byAccount[el.dataset.focusTotal]?.todayMs?`${time(totals.byAccount[el.dataset.focusTotal].todayMs)} focus`:'';
  if($('#focus-clock')) { const seconds=Math.max(0,Math.floor((Date.now()-state.active.since)/1000));$('#focus-clock').textContent=`${String(Math.floor(seconds/3600)).padStart(2,'0')}:${String(Math.floor(seconds/60)%60).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`; }
}
function showDialog(title,body) { dialogSequence++; delete dialog.dataset.account; dialog.innerHTML = `<div class="dialog-head"><h2 id="dialog-title">${esc(title)}</h2><button class="close" data-action="close" aria-label="Close dialog">×</button></div>${body}<div id="dialog-error" role="alert"></div>`; if (!dialog.open) dialog.showModal(); }
function showAdd() {
  showDialog('Add an account',`<p>Bring your subscriptions together. Each account keeps its own connection and history.</p><form id="add-form"><label class="field"><span>Provider</span><select name="provider" id="new-provider">${Object.entries(PROVIDERS).map(([key,p])=>`<option value="${key}">${p.name}</option>`).join('')}</select></label><div id="provider-description" class="provider-note">${esc(PROVIDERS.codex.description)}</div><label class="field"><span>Account name</span><input name="label" placeholder="e.g. Personal, Work, Studio" required maxlength="80" autocomplete="off"></label><label class="field"><span>Subscription / plan <span class="muted">(optional)</span></span><input name="subscription" placeholder="e.g. Pro, Plus, Team" maxlength="80" autocomplete="off"></label><div class="dialog-actions"><button type="button" class="quiet" data-action="close">Cancel</button><button class="primary" type="submit">Add account</button></div></form>`);
  $('#new-provider').addEventListener('change',e=>$('#provider-description').textContent=PROVIDERS[e.target.value].description);
  $('#add-form').addEventListener('submit',e=>runForm(e,async()=>{ const data=Object.fromEntries(new FormData(e.target)); const id=await call('add',data); await load(); showManage(id); }));
}
function showManage(id) {
  const a = state.accounts.find(a=>a.id === id); if (!a) return; const p = PROVIDERS[a.provider];
  showDialog(a.label,`<p>${esc(p.name)} · ${esc(p.mode)}</p><div class="provider-note">${esc(a.provider==='claude'?p.description:a.note || p.description)}</div>${a.provider==='claude'?`<div class="detail-actions"><button class="primary" data-action="claude-web" data-id="${id}">Connect Claude website · Free &amp; paid</button><button class="quiet" data-action="claude-login" data-id="${id}" ${a.loginPending?'disabled':''}>${a.loginPending?'Sign-in in progress…':a.claudeSignedIn?'Sign in again to Claude Code':'Sign in to Claude Code'}</button><button class="quiet" data-action="claude-dialog" data-id="${id}">${a.logPath?'Review local history':'Use existing Claude Code sign-in'}</button><button class="quiet" data-action="external" data-url="https://claude.ai">Open Claude chat ↗</button></div>`:''}<form id="edit-form"><label class="field"><span>Account name</span><input name="label" value="${esc(a.label)}" required maxlength="80"></label><label class="field"><span>Subscription / plan</span><input name="subscription" value="${esc(a.subscription)}" maxlength="80"></label>${a.provider==='copilot'?`<label class="field"><span>Billing model</span><select name="billingMode"><option value="ai_credit" ${a.billingMode==='ai_credit'?'selected':''}>AI credits</option><option value="premium_request" ${a.billingMode==='premium_request'?'selected':''}>Legacy premium requests</option></select></label>`:''}<button type="submit" class="small quiet">Save details</button></form>
  <div class="divider"></div><div class="detail-row"><b>Account</b><span>${esc(a.identity || (a.provider==='claude'?'No account detected yet':'Not connected'))}</span></div><div class="detail-row"><b>Last updated</b><span>${esc(age(a.lastSuccess))}</span></div><div class="detail-row"><b>Connection</b><span id="connection-status">${connectionStatus(a)}</span></div>
  ${a.logPath?`<div class="detail-row"><b>Local source</b><span>${esc(a.logPath)}</span></div>`:''}
  ${a.tokens?`<p>${esc(a.tokens.scope)}</p>`:''}
  <div class="detail-actions">${a.provider==='codex'?`<button class="primary" data-action="login" data-id="${id}">${a.connected?'Sign in again':'Sign in with ChatGPT'}</button>${a.loginPending?'<button data-action="cancel-login">Cancel sign-in</button>':''}`:''}${['copilot','openai-api','anthropic-api'].includes(a.provider)?`<button class="primary" data-action="key-dialog" data-id="${id}">${a.connected?'Replace credential':'Connect securely'}</button>`:''}${['codex','claude'].includes(a.provider)?`<button data-action="logs-dialog" data-id="${id}">${a.logPath?'Change log folder':'Select local logs'}</button>`:''}<button data-action="refresh-one" data-id="${id}">Refresh account</button>${a.logPath?`<button data-action="clear-logs" data-id="${id}">Unlink logs</button>`:''}</div>
  <p>Working time is estimated automatically from linked local activity. Gaps over five minutes are excluded and overlapping sessions count once. Copilot billing cannot report active time.</p><p>Focus time is measured separately by the timer you start here. It pauses after five minutes of computer inactivity, on lock, and on sleep. It does not estimate time from usage.</p>
  <div class="dialog-actions">${a.connected?`<button class="quiet" data-action="disconnect" data-id="${id}">${a.provider==='claude'?'Unlink from tracker':'Disconnect'}</button>`:''}<button class="danger" data-action="remove-dialog" data-id="${id}">Remove account</button></div>`);
  dialog.dataset.account=id; updateConnectionDialog();
  if (a.provider === 'copilot') {
    $('#edit-form button[type="submit"]').insertAdjacentHTML('beforebegin', `<div class="field"><label id="credit-allowance-label" for="credit-allowance">Monthly AI credit allowance (optional)</label><input id="credit-allowance" aria-describedby="credit-allowance-help" type="number" name="monthlyCredits" min="0.001" max="1000000000" step="any" value="${esc(a.monthlyCredits ?? '')}" placeholder="${copilotAllowance({...a, billingMode:'ai_credit', monthlyCredits:null}) ?? 'Enter the allowance shown by GitHub'}"><div id="credit-allowance-help" class="field-note">Leave blank to use your plan’s published allowance: Pro 1,500 · Pro+ 7,000 · Max 20,000. Used for AI credits only. The remaining balance is estimated; GitHub’s allowance may change. <button type="button" class="link" data-action="external" data-url="https://github.com/settings/billing/ai_usage">Check your allowance on GitHub ↗</button></div></div>`);
  }
  $('#edit-form').addEventListener('submit',e=>runForm(e,async()=>{ await call('edit',id,Object.fromEntries(new FormData(e.target))); await load(); toast('Account details saved.'); }));
}
function showClaudeWeb(id) {
  showDialog('Connect Claude website',`<p>Track Claude Free or paid-account limits from the account you use on claude.ai. No Claude Code subscription is needed.</p><ol class="connection-guide"><li><button class="link" data-action="claude-extension-folder">Open companion folder</button>. In Chrome or Edge, open Extensions → Manage extensions, enable Developer mode, choose Load unpacked, and select that folder.</li><li><button data-action="claude-web-code" data-id="${id}">Create connection code</button><div id="claude-web-code"></div></li><li>Open the companion from your browser’s Extensions menu. Paste the connection code and choose <b>Connect &amp; open Claude</b>. Sign in on Claude’s website.</li></ol><p>Keep a Claude tab open. Free-account usage may first appear after your next normal chat response. The companion never sends messages for you and shares only usage windows and an account identifier—not chat text, passwords, or cookies.</p><p class="field-note">This reads Claude’s website data, which can change. Missing readings stay unavailable. Reconnecting replaces this card’s previous website connection and clears imported history so accounts cannot be mixed.</p><div class="detail-actions"><button class="quiet" data-action="external" data-url="https://claude.ai/">Open Claude in browser ↗</button><button data-action="manage" data-id="${id}">Back</button></div>`);
}
async function showClaudeLogin(id) {
  showDialog('Sign in to Claude Code',`<p>Complete sign-in in your browser. Claude Code handles the secure connection and saves your login on this computer.</p><p>This signs into the installed Claude Code profile. If you choose a different account, Claude Code will use that account too.</p><p id="claude-login-status" role="status">Waiting for browser sign-in…</p><div class="detail-actions"><button data-action="claude-open-browser">Open sign-in page again</button><button data-action="claude-cancel" data-id="${id}">Cancel sign-in</button></div>`);
  const sequence=dialogSequence;dialog.dataset.claudePending='true';
  try {
    await call('claudeLogin',id);await load();
    if(dialog.open&&sequence===dialogSequence){delete dialog.dataset.claudePending;await showClaudeConnect(id);toast('Signed in with Claude. Confirm local history to see tokens and working time.');}
  } catch(e) {
    if(dialog.open&&sequence===dialogSequence){delete dialog.dataset.claudePending;$('#claude-login-status').textContent=e.message;$('#claude-login-status').className='error';dialog.querySelector('.detail-actions').innerHTML=`<button class="primary" data-action="claude-login" data-id="${id}">Try browser sign-in again</button><button data-action="manage" data-id="${id}">Back</button><button class="link" data-action="external" data-url="https://code.claude.com/docs/en/authentication">Sign-in help ↗</button>`;}
  }
}
async function showClaudeConnect(id) {
  showDialog('Link Claude Code',`<p>Link the Claude Code account signed in on this computer. This reads local token history and estimates active time. Claude chat messages, remaining subscription limits, and reset times are not synced.</p><p class="field-note">Claude Code requires an eligible subscription or separately billed API access. A free Claude chat account alone does not provide Claude Code access.</p><div id="claude-detection" aria-live="polite">Checking Claude Code sign-in…</div><div class="detail-actions"><button data-action="claude-login" data-id="${id}">Sign in to Claude Code</button><button data-action="external" data-url="https://code.claude.com/docs/en/authentication">Claude Code sign-in guide ↗</button><button data-action="logs-dialog" data-id="${id}">Select local logs</button><button data-action="manage" data-id="${id}">Back</button></div>`);
  const sequence=dialogSequence;
  let identity;
  try { identity=await call('claudeStatus'); }
  catch(e) { if(dialog.open&&sequence===dialogSequence) $('#claude-detection').textContent=e.message; return; }
  if(!dialog.open||sequence!==dialogSequence)return;
  if(!identity.loggedIn) { $('#claude-detection').textContent='Claude Code is not signed in. Use Sign in with Claude to connect in your browser.'; return; }
  $('#claude-detection').innerHTML=`<div class="provider-note"><strong>${esc(identity.email||'Signed-in Claude Code profile')}</strong><br>Plan reported by Claude Code: ${esc(identity.subscription||'Not reported')}<br>No sign-in credentials are copied to this tracker.</div><p>If this is not your account, choose Sign in with Claude below. Local history can include previous accounts: only link it if all sessions in this profile belong to this account.</p><form id="claude-link-form"><label class="check"><input type="checkbox" id="claude-source-confirm" required>I confirm this computer’s Claude Code history belongs to this account.</label><button class="primary" id="claude-link-submit" disabled>Link this account</button></form>`;
  $('#claude-source-confirm').addEventListener('change',e=>$('#claude-link-submit').disabled=!e.target.checked);
  $('#claude-link-form').addEventListener('submit',e=>runForm(e,async()=>{ await call('linkClaude',id,identity.email); await load(); if(dialog.open&&sequence===dialogSequence)showManage(id); toast('Claude Code history linked.'); }));
}
function showKey(id) {
  const a=state.accounts.find(a=>a.id===id);
  const url = a.provider==='copilot'?'https://github.com/settings/personal-access-tokens/new':a.provider==='openai-api'?'https://platform.openai.com/settings/organization/admin-keys':'https://platform.claude.com/settings/admin-keys';
  const setupGuide = a.provider === 'copilot' ? `
    <section class="connection-guide" aria-labelledby="token-setup-title">
      <h3 id="token-setup-title">Create your GitHub token</h3>
      <ol>
        <li><strong>Token name:</strong> <code>AI Usage Tracker</code></li>
        <li><strong>Resource owner:</strong> your account.</li>
        <li><strong>Expiration:</strong> 30 days is fine; reconnect when it expires.</li>
        <li><strong>Repository access:</strong> leave <strong>Public repositories</strong> selected.</li>
        <li>Add <strong>Account permissions → Plan → Read-only</strong>. No repository write permissions are needed. <button type="button" class="link" data-action="external" data-url="https://docs.github.com/en/rest/billing/usage#get-billing-ai-credit-usage-report-for-a-user">Required permission ↗</button></li>
        <li>Generate the token, paste it into the password field below, then click <strong>Save &amp; connect</strong>.</li>
      </ol>
    </section>` : '';
  showDialog('Connect securely',`<p>${esc(PROVIDERS[a.provider].description)}</p><button class="link" data-action="external" data-url="${url}">Open provider credential settings ↗</button>${setupGuide}<form id="key-form"><label class="field"><span>${a.provider==='copilot'?'Fine-grained personal access token':'Organization admin key'}</span><input type="password" name="key" required autocomplete="off" spellcheck="false" maxlength="20000" placeholder="Enter credential here, never in chat"><div class="field-note">Encrypted with ${navigator.platform.startsWith('Win')?'Windows DPAPI':'your OS keychain'}. The saved key is never sent back to this screen.</div></label>${!state.secureStorage?'<div class="error">OS secure storage is unavailable. Unlock the keychain to continue.</div>':''}<div class="dialog-actions"><button type="button" data-action="manage" data-id="${id}">Back</button><button type="submit" class="primary" ${!state.secureStorage?'disabled':''}>Save & connect</button></div></form>`);
  $('#key-form').addEventListener('submit',e=>runForm(e,async()=>{ const input=e.target.elements.key; const key=input.value; input.value=''; await call('connectKey',id,key); await load(); showManage(id); const a=state.accounts.find(a=>a.id===id); if(a.error) $('#dialog-error').innerHTML=`<div class="error">${esc(a.error)}</div>`; else toast('Connection refreshed.'); }));
}
function showSettings() {
  showDialog('Settings',`<form id="settings-form"><label class="field"><span>Automatic refresh</span><select name="pollSeconds">${[60,300,900,3600].map(s=>`<option value="${s}" ${state.settings.pollSeconds===s?'selected':''}>Every ${s/60} minutes</option>`).join('')}</select></label><label class="check"><input type="checkbox" name="closeToTray" ${state.settings.closeToTray?'checked':''}>Keep running in the tray / menu bar when the window closes.</label><div class="provider-note">Refreshes continue while this app is running. Providers can delay reports or apply a cooldown. Manual refreshes are limited to once every 10 seconds per account.</div><div class="dialog-actions"><button type="submit" class="primary">Save settings</button></div></form><div class="divider"></div><h3>Codex CLI</h3><p>The official CLI handles browser sign-in and stores each account in a separate OS keyring profile. Install the CLI first, then select its native executable if automatic discovery fails.</p><p>${esc(state.settings.codexPath || 'Automatic discovery from installed CLI')}</p><div class="detail-actions"><button data-action="choose-codex">Choose executable</button><button class="quiet" data-action="external" data-url="https://developers.openai.com/codex/cli">Installation guide ↗</button></div><p>Token dates use UTC to match provider reports. Working time uses your computer’s local calendar. Local logs may contain several accounts: link only a folder you can attribute to one account.</p>`);
  $('#settings-form').addEventListener('submit',e=>runForm(e,async()=>{ const f=new FormData(e.target); await call('settings',{pollSeconds:Number(f.get('pollSeconds')),closeToTray:f.has('closeToTray')}); await load(); dialog.close(); toast('Settings saved.'); }));
}
async function runForm(event,fn) { event.preventDefault(); const form=event.target; const buttons=[...form.querySelectorAll('button')]; buttons.forEach(b=>b.disabled=true); try { await fn(); } catch(e) { showError(e); } finally { buttons.forEach(b=>b.disabled=false); } }
function showError(e) { if(dialog.open) $('#dialog-error').innerHTML=`<div class="error">${esc(e.message)}</div>`; else toast(e.message); }
document.addEventListener('click',async e=> {
  const button=e.target.closest('[data-action]'); if(!button || button.disabled) return;
  const { action, id, url }=button.dataset;
  try {
    if(action==='close') return dialog.close();
    if(action==='add') return showAdd();
    if(action==='manage') return showManage(id);
    if(action==='filter') { provider=id; subscription='all'; activityMetric='auto'; return render(); }
    if(action==='reset-filters') { provider='all'; subscription='all'; return render(); }
    if(action==='settings') return showSettings();
    if(action==='metric') { if(Object.hasOwn(METRICS,id)){activityMetric=id;render();} return; }
    if(action==='window-toggle') return await call('windowMode',window.innerWidth<700?'expand':'compact');
    if(action==='pin') { await call('windowMode','pin'); return await load(); }
    if(action==='key-dialog') return showKey(id);
    if(action==='claude-web') return showClaudeWeb(id);
    if(action==='claude-extension-folder') { await call('openClaudeExtension');return; }
    if(action==='claude-web-code') { const {code}=await call('prepareClaudeWeb',id);await load();if($('#claude-web-code'))$('#claude-web-code').innerHTML=`<label class="field"><span>Copy this into the browser companion (valid for 10 minutes)</span><input readonly type="text" value="${esc(code)}" aria-label="Browser companion connection code"></label>`;document.querySelector('#claude-web-code input')?.addEventListener('focus',e=>e.target.select());return; }
    if(action==='claude-login') return await showClaudeLogin(id);
    if(action==='claude-cancel') { await call('cancelClaudeLogin');delete dialog.dataset.claudePending;return showManage(id); }
    if(action==='claude-open-browser') return await call('openClaudeBrowser');
    if(action==='claude-dialog') return await showClaudeConnect(id);
    if(action==='external') return await call('external',url);
    if(action==='daily') { const data=activity(); return showDialog(`Daily ${data.label.toLowerCase()} values`,`<p>Exact reported totals for the selected sources. ${['focus','active'].includes(data.metric)?'Dates use your local calendar.':'Dates use UTC. Missing sources mean a partial total.'}</p><table class="token-table"><thead><tr><th>Date</th><th>${data.label}</th><th>Sources</th></tr></thead><tbody>${data.series.slice().reverse().map(d=>`<tr><td>${d.day}</td><td>${d.total===null?'Unavailable':number(d.total)}</td><td>${d.reporting} / ${d.accounts}</td></tr>`).join('')}</tbody></table>`); }
    if(action==='logs-dialog') { showDialog('Link local token history',`<p>Select the ${state.accounts.find(a=>a.id===id).provider==='codex'?'Codex sessions':'Claude Code projects'} folder for this account. Reads JSONL token counters; prompts and responses are not stored or sent anywhere.</p><div class="provider-note">Local logs do not contain reliable subscription identity. If you switched accounts in this folder, its tokens cannot be attributed to a single subscription. Use separate folders for each account.</div><label class="check"><input type="checkbox" id="source-confirm">I confirm that the selected folder belongs to this account.</label><div class="dialog-actions"><button data-action="manage" data-id="${id}">Back</button>${state.accounts.find(a=>a.id===id).provider==='codex'?`<button id="detected-logs-button" data-action="detected-logs" data-id="${id}" disabled>Use this computer’s Codex history</button>`:''}<button id="choose-logs-button" class="primary" data-action="choose-logs" data-id="${id}" disabled>Choose folder</button></div>`); $('#source-confirm').addEventListener('change',e=>{ $('#choose-logs-button').disabled=!e.target.checked; if($('#detected-logs-button')) $('#detected-logs-button').disabled=!e.target.checked; }); return; }
    if(action==='remove-dialog') { const a=state.accounts.find(a=>a.id===id); return showDialog('Remove account?',`<p>Remove <b>${esc(a.label)}</b>, its saved readings, credentials, and recorded focus time from this app? Original log files stay on your computer.</p><div class="dialog-actions"><button data-action="manage" data-id="${id}">Cancel</button><button class="danger" data-action="remove" data-id="${id}">Remove account & history</button></div>`); }
    button.disabled=true;
    if(action==='refresh' || action==='refresh-one') { await call('refresh',id); await load(); toast('Refresh completed. Account cards show any connection errors or cooldowns.'); }
    if(action==='start') { await call('start',id); await load(); toast('Focus timer started. It pauses on idle, lock, or sleep.'); }
    if(action==='stop') { await call('stop'); await load(); }
    if(action==='login') { await call('login',id); await load(); showManage(id); toast('Complete sign-in in your browser. Each account uses its own profile.'); }
    if(action==='cancel-login') { await call('cancelLogin'); await load(); dialog.close(); }
    if(action==='detected-logs') { await call('detectedLogs',id); await load(); showManage(id); toast('Local token history linked.'); }
    if(action==='choose-logs') { await call('chooseLogs',id); await load(); showManage(id); }
    if(action==='clear-logs') { await call('clearLogs',id); await load(); showManage(id); }
    if(action==='choose-codex') { await call('chooseCodex'); await load(); showSettings(); }
    if(action==='disconnect') { await call('disconnect',id); await load(); showManage(id); }
    if(action==='remove') { await call('remove',id); await load(); dialog.close(); }
  } catch(e) { showError(e); } finally { if(button.isConnected) button.disabled=false; }
});
dialog.addEventListener('close',()=>{if(dialog.dataset.claudePending){delete dialog.dataset.claudePending;void call('cancelClaudeLogin').catch(()=>{});}});
api.onChange(()=>void load().catch(showError));
setInterval(updateClock,1000);
setInterval(()=>{if(state?.accounts.some(a=>a.claudeWeb&&a.quotas?.some(q=>q.resetsAt<=Date.now())))render();},15000);
load().catch(e=>{ $('#main').innerHTML=`<div class="error">${esc(e.message)}</div>`; });
